name: pprof-web
fullNameOverride: ""
replicaCount: 1
containerPort: 8080
image:
  repository: ghcr.io/wzxjohn/pprof-web
  tag: ""
  pullPolicy: IfNotPresent
imagePullSecrets: [ ]
service:
  fullNameOverride: ""
  port: 8080
  targetPort: 8080
  type: ClusterIP
  sessionAffinity: None
  annotations: { }
ingress:
  enabled: false
  annotations: { }
  hosts:
    - host: ""
      paths: [ ]
  tls: [ ]
liveness:
  initialDelaySeconds: 30
  periodSeconds: 5
readiness:
  initialDelaySeconds: 10
  periodSeconds: 1
env: { }
strategy: { }
resources: { }
nodeSelector: { }
tolerations: [ ]
affinity: { }

pv:
  enabled: false
  storageClassName: ""
  storageCapacity: 10Gi
  hostPath: { }
  config: { }

config:
  tempPath: "/tmp/pprof-web"
