{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pprof.web.fullName" . }}-pvc
  labels:
    {{- include "pprof.web.labels" . | nindent 4 }}
    pvc: {{ include "pprof.web.fullName" . }}-pvc
spec:
  accessModes:
    {{- toYaml .Values.pvc.accessModes | nindent 4 }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvc.storageCapacity  }}
  {{- if .Values.pvc.config }}
  {{- toYaml .Values.pvc.config | nindent 2 }}
  {{- end }}
{{- end }}
